/**
 * ─────────────────────────────────────────────────────────────
 *  WITH WARM REGARDS — data.js
 *  Your persistent content store.
 *
 *  HOW TO BACK UP:
 *    In admin.html, click "Export data.js" → save the file here,
 *    replacing this file. Your posts and about page are now saved.
 *
 *  HOW TO RESTORE:
 *    Just keep this file in the same folder as index.html and
 *    admin.html. It loads automatically and seeds localStorage
 *    on first visit (or after a browser data clear).
 *
 *  DO NOT edit this file by hand unless you know what you're doing.
 * ─────────────────────────────────────────────────────────────
 */

const WWR_DATA = {
  exportedAt: null,
  posts: [],
  about: {}
};
